version: '3'
services:
  db:
    build: .
    ports:
      - "5040:5040"
    environment:
      MYSQL_DATABASE: gruppe4 
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./sql/initDB.sql:/docker-entrypoint-initdb.d/initDB.sql
